// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nonwsmuudvxiowfqpmor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vbndzbXV1ZHZ4aW93ZnFwbW9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNDYwNDksImV4cCI6MjA1ODkyMjA0OX0.qrAC6ZWrfCCDrSmvi_oOQ0K_sYhOuHvimlR5_qeGHWM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);