// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arxjykuhctypzhyzpwya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyeGp5a3VoY3R5cHpoeXpwd3lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNTE0NDEsImV4cCI6MjA1ODcyNzQ0MX0.NOrZLO3Z6jqQm8b_AMvhEHLS0o5kaUay9Ndts6NihVg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);